"""Citation bijection for T'.

T' cites with pandoc @keys and its References section is generated by citeproc
at build time, so the AM-era check -- author-year strings against a typed
References list -- no longer describes this manuscript. What must hold now:

  (a) every cited key resolves in references.bib          [else a dangling cite]
  (b) every bib entry is cited                            [else an orphan entry]
  (c) no bare author-year citation survives in the prose  [else an invisible
      citation: it reads as a citation and citeproc will never render it]

(c) is the one that caught a real defect: three classical works were cited as
"(Robinson 1950)" in inherited prose, which renders as literal parentheses and
appears in no References list.
"""

import re
import sys
from pathlib import Path

HERE = Path(__file__).parent
SRC = HERE / "draft_t1.md"
BIB = HERE / "references.bib"

# "(Name 1999)" or "(Name and Name 1999)" or "(Name et al. 1999)", not preceded
# by an @ and not inside a markdown link. Deliberately conservative: it must not
# fire on ordinary parenthesised years like "(2026)".
BARE = re.compile(
    r"\((?!see )(?:[A-Z][A-Za-z\u00C0-\u024F\-]+"
    r"(?:,? (?:and |& |et al\.? ?)?[A-Z][A-Za-z\u00C0-\u024F\-]+)*)"
    r" \(?(?:19|20)\d{2}\)?\)"
)


def check():
    md = SRC.read_text()
    cited = set(re.findall(r"@([a-zA-Z][a-zA-Z0-9_:.\-]*\d{4}[a-zA-Z]*)", md))
    keys = set(re.findall(r"^@\w+\{([^,]+)", BIB.read_text(), re.M))
    fails = []
    for k in sorted(cited - keys):
        fails.append(f"cited key not in references.bib: {k}")
    for k in sorted(keys - cited):
        fails.append(f"orphan bib entry, cited nowhere: {k}")
    # strip fenced code and the dossier-style quoted blocks before scanning prose
    prose = re.sub(r"`[^`]*`", "", md)
    for m in BARE.finditer(prose):
        fails.append(f"bare author-year citation, invisible to citeproc: {m.group(0)}")
    return cited, keys, fails


def main():
    cited, keys, fails = check()
    print(f"cited keys : {len(cited)}")
    print(f"bib entries: {len(keys)}")
    if fails:
        print(f"\nFAIL  citation bijection: {len(fails)} problem(s)")
        for f in fails:
            print(f"        {f}")
        return 1
    print("\nok    citation bijection: every cited key resolves, "
          "every entry is cited, no bare author-year forms")
    return 0


if __name__ == "__main__":
    sys.exit(main())
